### ISSUE TITLE
bro log file not exist caused firemain crash

### ISSUE THREAD

**Issue by MelvinTo** [firewalla/firewalla#213]
INFO 2017-06-20 17:44:20 Discovery: Discover:NatScan
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/blog/current/software.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at /home/pi/.node_modules/always-tail/index.js:225:29
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
INFO 2017-06-20 17:45:42 Main: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO 2017-06-20 17:45:42 Main: Main Starting
INFO 2017-06-20 17:45:42 Main: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO 2017-06-20 17:45:50 Main: Waiting for cloud token created by kickstart job...
INFO 2017-06-20 17:45:50 Bone: Cloud token is ready
INFO 2017-06-20 17:45:51 SensorLoader: Installing Sensor: DHCPSensor
INFO 2017-06-20 17:45:51 Dhcpdump: DHCPExtention:Install cd /home/pi/firewalla/extension/d

**Comment by jerrchen** [comment]
most of the time  log are not there when openned, wondering why it is special here and the crash

**Comment by MelvinTo** [comment]
just added a try catch in always-tail module to prevent from crash

https://github.com/MelvinTo/always-tail/commit/e021c8f337d77024b60db8bf2d8d30837e3ef7d4
