### ISSUE TITLE
crash in dnsmasq when dealing with overlay dhcp mode

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#240]
TypeError: Cannot read property 'state' of undefined
    at dnsmasq (/home/pi/firewalla/net2/PolicyManager.js:429:15)
    at execute (/home/pi/firewalla/net2/PolicyManager.js:609:16)
    at /home/pi/firewalla/net2/HostManager.js:1943:31
    at Command.callback (/home/pi/firewalla/net2/HostManager.js:19

This is a brand new system, configured to use overlay dhcp mode.  This crash happens when try to block a device.

**Comment by MelvinTo** [comment]
fixed in #241
