### ISSUE TITLE
strange crash during overlay mode

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#254]
INFO 2016-02-11 16:33:50 BroDetect: Start watching intel log
INFO 2016-02-11 16:33:50 BroDetect: Start watching notice log
dgram.js:464
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:907:11)
    at Socket.addMembership (dgram.js:464:11)
    at Socket.<anonymous> (/home/pi/.node_modules/bonjour/node_modules/multicast-dns/index.js:52:14)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at startListening (dgram.js:121:10)
    at dgram.js:221:7
    at nextTickCallbackWith3Args (node.js:522:9)
    at process._tickCallback (node.js:428:17)
INFO 2016-02-11 16:33:56 Main: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
INFO 2016-02-11 16:33:56 Main: Main Starting 
INFO 2016-02-11 16:33:56 Main: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
^C

**Comment by jerrchen** [comment]
This problem occurs when some how the board was powered by the serial port :(  it still runs, just not enough juice.   Ethernet wasn't coming up ... human error
