### ISSUE TITLE
rejection errors for alarm

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#295]
actionobj:
   { title: '42.7.26.91 appears to be guessing SSH passwords (seen in 30 connections).',
     actions: [ 'ignore' ],
     src: '42.7.26.91',
     dst: undefined,
     note: 'SSH::Password_Guessing',
     target: undefined,
     msg: '42.7.26.91 appears to be guessing SSH passwords (seen in 30 connections).',
     obj: 
      { ts: 1503718979.175245,
        note: 'SSH::Password_Guessing',
        msg: '42.7.26.91 appears to be guessing SSH passwords (seen in 30 connections).',
        sub: 'Sampled servers:  192.168.2.227, 192.168.2.227, 192.168.2.227, 192.168.2.227, 192.168.2.227',
        src: '42.7.26.91',
        peer_descr: 'bro',
        actions: [Object],
        suppress_for: 3600,
        dropped: false },
     shname: undefined,
     dhname: null },
  ts: 1503718993.202 }
Unhandled rejection Error: requiring p.device.ip
    at enrichDeviceInfo (/home/pi/firewalla/alarm/AlarmManager2.js:697:31)
    at /home/pi/firewalla/net2/BroDetect.js:1286:27
    at DNSManager.resolvehost (/home/pi/firewalla/net2/DNSManager.js:205:11)
    at /home/pi/firewalla/net2/BroDetect.js:1273:32
    at /home/pi/firewalla/net2/DNSManager.js:194:25
    at Command.callback (/home/pi/firewalla/net2/DNSManager.js:140:17)
    at normal_reply (/home/pi/.node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/home/pi/.node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/home/pi/.node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/home/pi/.node_modules/redis/node_modules/redis-parser/lib/parser.js:415:12)
    at Socket.<anonymous> (/home/pi/.node_modules/redis/index.js:267:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)
Unhandled rejection Error: requiring p.device.ip
    at enrichDeviceInfo (/home/pi/firewalla/alarm/AlarmManager2.js:697:31)
    at /home/pi/firewalla/net2/BroDetect.js:1286:27
    at DNSManager.resolvehost (/home/pi/firewalla/net2/DNSManager.js:205:11)
    at /home/pi/firewalla/net2/BroDetect.js:1273:32
    at /home/pi/firewalla/net2/DNSManager.js:194:25
    at Command.callback (/home/pi/firewalla/net2/DNSManager.js:140:17)
    at normal_reply (/home/pi/.node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/home/pi/.node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/home/pi/.node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/home/pi/.node_modules/redis/node_modules/redis-parser/lib/parser.js:415:12)
    at Socket.<anonymous> (/home/pi/.node_modules/redis/index.js:267:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)

**Comment by jerrchen** [comment]
INFO 2017-08-26 05:21:59 AlarmManager: alarm:ip4: alarm:ip4:undefined
INFO 2017-08-26 05:21:59 AlarmManager: alarm:check: undefined { msg: '5.101.40.10 appears to be guessing SSH passwords (seen in 30 connections).',
  id: 'eedf9398-c7b3-4c4e-9096-2f1214ebc5ee',
  alarmtype: 'notice',
  alarmseverity: 'info',
  severityscore: '0',
  actionobj:
   { title: '5.101.40.10 appears to be guessing SSH passwords (seen in 30 connections).',
     actions: [ 'ignore' ],
     src: '5.101.40.10',
     dst: undefined,
     note: 'SSH::Password_Guessing',
     target: undefined,
     msg: '5.101.40.10 appears to be guessing SSH passwords (seen in 30 connections).',
     obj:
      { ts: 1503724916.422161,
        note: 'SSH::Password_Guessing',
        msg: '5.101.40.10 appears to be guessing SSH passwords (seen in 30 connections).',
        sub: 'Sampled servers:  192.168.2.227, 192.168.2.227, 192.168.2.227, 192.168.2.227, 192.168.2.227',
        src: '5.101.40.10',
        peer_descr: 'bro',
        actions: [Object],
        suppress_for: 3600,
        dropped: false },
     shname: undefined,
     dhname: null },
  ts: 1503724919.416 }
Unhandled rejection Error: requiring p.device.ip
    at enrichDeviceInfo (/home/pi/firewalla/alarm/AlarmManager2.js:697:31)
    at /home/pi/firewalla/net2/BroDetect.js:1286:27
    at DNSManager.resolvehost (/home/pi/firewalla/net2/DNSManager.js:205:11)
    at /home/pi/firewalla/net2/BroDetect.js:1273:32
    at /home/pi/firewalla/net2/DNSManager.js:194:25
    at Command.callback (/home/pi/firewalla/net2/DNSManager.js:140:17)
    at normal_reply (/home/pi/.node_modules/redis/index.js:714:21)
    at RedisClient.return_reply (/home/pi/.node_modules/redis/index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (/home/pi/.node_modules/redis/index.js:188:18)
    at JavascriptRedisParser.execute (/home/pi/.node_modules/redis/node_modules/redis-parser/lib/parser.js:415:12)
    at Socket.<anonymous> (/home/pi/.node_modules/redis/index.js:267:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)
INFO 2017-08-26 05:21:59 HostManager: HostManager:isIgnoredIPs: [ '5.101.40.10', undefined, undefined, null, undefined, undefined ] false
INFO 2017-08-26 05:21:59 AlarmManager: Error on alarms alarm:ip4:undefined null
INFO 2017-08-26 05:21:59 AlarmManager: alarm:check:noprevious undefined
INFO 2017-08-26 05:21:59 DestIPFoundHook: 5IP Addresses are analyzed with intels
INFO 2017-08-26 05:21:59 AlarmManager: alarm:ip4: alarm:ip4:0.0.0.0
INFO 2017-08-26 05:21:59 AlarmManager: alarm:check: 0.0.0.0 { msg: '5.101.40.10 appears to be guessing SSH passwords (seen in 30 connections).',
  id: '325662cb-fda5-4163-8f63-c8b1a566dcd3',
