### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#405]
INFO 2017-10-13 00:01:40 FlowAggregationSensor: Aggregating 00:05:04:03:02:01 flows between 12:00:00 AM and 12:10:00 AM
Unhandled rejection TypeError: Cannot read property 'lh' of null
    at FlowTool.getDestIP (/home/pi/firewalla/net2/FlowTool.js:506:12)
    at /home/pi/firewalla/sensor/FlowAggregationSensor.js:387:29
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9)
INFO 2017-10-13 00:01:43 UPNPSensor: UPNP mapping is updated, 15 entries
INFO 2017-10-13 00:01:50 NmapSensor: Analyzing scan result...

**Comment by jerrchen** [comment]
- didn't fix the core problem of why the null is passed

**Comment by MelvinTo** [comment]
already fixed.
