### ISSUE TITLE
Device error when fetching traffic details

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#614]
```
ERROR 2017-12-22 03:39:47 Netbot: Got error before simpleTxData: TypeError: Cannot read property 'country' of null
    at async (/home/pi/firewalla/net2/FlowTool.js:440:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9) TypeError: Cannot read property 'country' of null
    at async (/home/pi/firewalla/net2/FlowTool.js:440:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9)
```

**Comment by starsy** [comment]
closed w/ https://github.com/firewalla/firewalla/pull/616 & https://github.com/firewalla/firewalla/pull/615
