### ISSUE TITLE
Device error when fetching traffic details

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#617]
Another null pointer
```
ERROR 2017-12-23 01:08:02 Netbot: Got error before simpleTxData: ReferenceError: unhashedData2 is not defined
    at async (/home/pi/firewalla/controllers/netbot.js:1200:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9) ReferenceError: unhashedData2 is not defined
    at async (/home/pi/firewalla/controllers/netbot.js:1200:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9)
```

**Comment by starsy** [comment]
No unhashedData2 defined in the validateFlowAppIntel() function, where should it come from?

```node
  validateFlowAppIntel(json) {
    return async(() => {
      // await (bone.flowgraphAsync(...))
      let flows = json.flows

      let hashCache = {}


      let appFlows = flows.appDetails

      if(Object.keys(appFlows).length > 0) {
        flowUtil.hashIntelFlows(appFlows, hashCache)

        let data = await (bone.flowgraphAsync('summarizeApp', appFlows))
        let unhashedData = flowUtil.unhashIntelFlows(data, hashCache)

        flows.appDetails = unhashedData
        flows.categoryDetails = unhashedData2
      }
    })()
  }
```

**Comment by MelvinTo** [comment]
production doesn't have this issue. no need to patch

**Comment by starsy** [comment]
closed w/ https://github.com/firewalla/firewalla/commit/13ab1088fc945f15d3360fa3b5fc10438123ed94
