### ISSUE TITLE
Slow/Timeout on UI when Showing Traffic Details

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#626]
When touching the traffic graph to show details, it is very slow or getting timeout.   

```
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 182.39.5.255, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 182.38.127.78, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 59.61.172.220, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 27.154.73.189, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 59.56.40.185, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 121.205.170.105, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 220.160.115.69, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 218.66.82.56, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 121.225.193.151, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 117.88.2.211, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 114.88.130.187, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 180.102.151.108, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 49.85.233.54, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 60.187.107.194, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 122.242.144.93, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 114.96.9.88, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 60.186.241.61, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 125.111.44.23, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 180.175.226.80, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 47.100.122.106, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 116.226.174.121, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 218.61.39.110, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 150.138.229.159, checking intels...
INFO 2017-12-26 14:19:25 DestIPFoundHook: Found new IP 119.188.13.180, checking intels...


ERROR 2017-12-26 14:19:41 Bone: Error while requesting  { Error: ETIMEDOUT
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:759:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5) code: 'ETIMEDOUT', connect: false } Error
    at Request.request (/home/pi/firewalla/lib/Bone.js:488:19)
    at Request._callback (/home/pi/.node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/home/pi/.node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/pi/.node_modules/requestretry/index.js:133:10)
    at self.callback (/home/pi/.node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:762:12)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
INFO 2017-12-26 14:19:41 Bone: undefined
ERROR 2017-12-26 14:19:41 Bone: Error while requesting  { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/.node_modules/request/request.js:776:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitRequestTimeout (_http_client.js:644:42)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:400:8)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5) code: 'ESOCKETTIMEDOUT', connect: false } Error
    at Request.request (/home/pi/firewalla/lib/Bone.js:488:19)
    at Request._callback (/home/pi/.node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/home/pi/.node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/pi/.node_modules/requestretry/index.js:133:10)
    at self.callback (/home/pi/.node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at ClientRequest.<anonymous> (/home/pi/.node_modules/request/request.js:779:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitRequestTimeout (_http_client.js:644:42)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:400:8)
INFO 2017-12-26 14:19:41 Bone: undefined
ERROR 2017-12-26 14:19:41 Bone: Error while requesting  { Error: ETIMEDOUT
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:759:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5) code: 'ETIMEDOUT', connect: false } Error
    at Request.request (/home/pi/firewalla/lib/Bone.js:488:19)
    at Request._callback (/home/pi/.node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/home/pi/.node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/pi/.node_modules/requestretry/index.js:133:10)
    at self.callback (/home/pi/.node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:762:12)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
INFO 2017-12-26 14:19:41 Bone: undefined
ERROR 2017-12-26 14:19:41 Bone: Error while requesting  { Error: ETIMEDOUT
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:759:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5) code: 'ETIMEDOUT', connect: false } Error
    at Request.request (/home/pi/firewalla/lib/Bone.js:488:19)
    at Request._callback (/home/pi/.node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/home/pi/.node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/pi/.node_modules/requestretry/index.js:133:10)
    at self.callback (/home/pi/.node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Timeout._onTimeout (/home/pi/.node_modules/request/request.js:762:12)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
INFO 2017-12-26 14:19:41 Bone: undefined
ERROR 2017-12-26 14:19:41 Bone: Error while requesting  { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/.node_modules/request/request.js:776:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitRequestTimeout (_http_client.js:644:42)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:400:8)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5) code: 'ESOCKETTIMEDOUT', connect: false } Error
    at Request.request (/home/pi/firewalla/lib/Bone.js:488:19)
    at Request._callback (/home/pi/.node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/home/pi/.node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/home/pi/.node_modules/requestretry/index.js:133:10)
    at self.callback (/home/pi/.node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at ClientRequest.<anonymous> (/home/pi/.node_modules/request/request.js:779:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at ClientRequest.emit (events.js:207:7)
    at TLSSocket.emitRequestTimeout (_http_client.js:644:42)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket.Socket._onTimeout (net.js:400:8)
```

**Comment by starsy** [comment]
The root cause is checking intel for IPs is flooding bone, thus causing lots of requests timeout. Bone is refusing these quick flooding requests. 

The situation is expected to get worse and bone cannot scale when lots of new users getting on-board. 

Need to add batch query mechanism between walla and bone.

**Comment by starsy** [comment]
Proof of wall not being the root cause.

```shell
#!/bin/bash

while true; do
  curl -s -X POST \
    https://<intel check url> \
    -H 'Authorization: Bearer <ignored>' \
    -H 'Content-Type: application/json' \
    -d '{ "flowlist":   <payload>  }'
  if [ $? -ne 0 ]; then
    echo "Error"
  fi
done
```
No "Error" is printed
```
pi@Firewalla:~/test$ ./test.sh
[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]
````

**Comment by jerrchen** [comment]
likely a network issue.  The bone cluster is load balanced.  In case of any device is flooding, it will return 429 to throttle.   429 only happen to devices that do heavy p2p, and only during init stage.

**Comment by starsy** [comment]
network issue cannot explain why single request always successful, batch request always something fail.
