### ISSUE TITLE
Unhandled null Intel when processIP() fails

### ISSUE THREAD

**Issue by starsy** [firewalla/firewalla#630]
```
ERROR 2017-12-27 06:07:00 Netbot: Got error before simpleTxData: TypeError: Cannot read property 'country' of null
    at async (/home/pi/firewalla/net2/NetBotTool.js:335:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9) TypeError: Cannot read property 'country' of null
    at async (/home/pi/firewalla/net2/NetBotTool.js:335:33)
    at tryBlock (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:39:33)
    at runInFiber (/home/pi/.node_modules/asyncawait/src/async/fiberManager.js:26:9)
```

**Comment by starsy** [comment]
closed w/ https://github.com/firewalla/firewalla/pull/631
