### ISSUE TITLE
(Production Crash) In NAT_UPNP

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#646]
"type": "FIREWALLA.MAIN.exception",
    "msg": "Cannot read property 'NewRemoteHost' of undefined",
    "stack": "TypeError: Cannot read property 'NewRemoteHost' of undefined\n    at /home/pi/.node_modules/nat-upnp/lib/nat-upnp/client.js:111:31\n    at /home/pi/.node_modules/nat-upnp/lib/nat-upnp/device.js:158:9\n    at Parser.<anonymous> (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/lib/xml2js.js:199:18)\n    at emitOne (events.js:115:13)\n    at Parser.emit (events.js:210:7)\n    at SAXParser.saxParser.onclosetag (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/lib/xml2js.js:183:24)\n    at emit (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:624:35)\n    at emitNode (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:629:5)\n    at closeTag (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:889:7)\n    at SAXParser.write (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/node_modules/sax/lib/sax.js:1436:13)\n    at Parser.exports.Parser.Parser.parseString (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/lib/xml2js.js:211:31)\n    at Parser.parseString (/home/pi/.node_modules/nat-upnp/node_modules/xml2js/lib/xml2js.js:6:61)\n    at Request._callback (/home/pi/.node_modules/nat-upnp/lib/nat-upnp/device.js:149:14)\n    at Request.self.callback (/home/pi/.node_modules/nat-upnp/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (/home/pi/.node_modules/nat-upnp/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (/home/pi/.node_modules/nat-upnp/node_modules/request/request.js:1085:12)\n    at Object.onceWrapper (events.js:314:30)\n    at emitNone (events.js:110:20)"

**Comment by jerrchen** [comment]
fixed  by melvin
