### ISSUE TITLE
(Production) Issue with Redis connection exception

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#647]
"version": 1.93,
    "type": "exception",
    "msg": "Redis connection to 127.0.0.1:6379 failed - write EPIPE",
    "stack": "Error: Redis connection to 127.0.0.1:6379 failed - write EPIPE\n    at _errnoException (util.js:1021:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:860:14)"
  }
}

**Comment by jerrchen** [comment]
likely dead card problem where redis never came up.
