### ISSUE TITLE
(Production exception) Unable to find module in Firemon

### ISSUE THREAD

**Issue by jerrchen** [firewalla/firewalla#649]
"type": "FIREWALLA.MON.exception",
    "msg": "Cannot find module './apply'",
    "stack": "Error: Cannot find module './apply'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/home/pi/.node_modules/nat-upnp/node_modules/async/index.js:8:14)\n    at Module._compile (module.js:624:30)\n    at Object.Module._extensions..js (module.js:635:10)\n    at Module.load (module.js:545:32)\n    at tryModuleLoad (module.js:508:12)\n    at Function.Module._load (module.js:500:3)\n    at Module.require (module.js:568:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/home/pi/.node_modules/nat-upnp/lib/nat-upnp/client.js:2:13)\n    at Module._compile (module.js:624:30)\n    at Object.Module._extensions..js (module.js:635:10)\n    at Module.load (module.js:545:32)"

**Comment by jerrchen** [comment]
module corruption, fixed in latest to prevent corruption
